### ISSUE TITLE
Avoid confusing network engineers

### ISSUE THREAD

**Issue by mattmathis** [m-lab/ndt-server#125]
Make it unambiguous if the test is using IPv4 or IPv6.  Many engineers have baked in assumptions that are wrong for IPv6.   (This also requires client changes).

**Comment by bassosimone** [comment]
My understanding is that, if we're using IPv6, at least one of the two endpoints should be IPv6. It may be that the client is into an IPv4 cloud, the server is also into an IPv4 cloud, and that the two clouds are communicating via IPv6 using tunnelling, but I don't know how to address this case. Does my reasoning make sense, @mattmathis, or am I missing something?

**Comment by bassosimone** [comment]
I understand. I believe this is, in a way, more a UI issue though. Since, as you say, it's possible to infer whether it's v4 or v6, I believe we don't need to change the message we transfer but, rather, we just need to make sure that the client adds the v4/v6 information when required. Does it make sense?

**Comment by pboothe** [comment]
So you would like "address family" to be a top-level attribute in the results instead of part of the (joinable) tcp-info dataset? Like min RTT and avg throughput are currently?

**Comment by stephen-soltesz** [comment]
@mattmathis can you check whether the current data format looks good to you?

**Comment by mattmathis** [comment]
This issue refers to an old client that was embedded in the server.   Has been removed.
