### ISSUE TITLE
NDT-server client error rates

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt-server#134]
Frequency of errors reported by PanicOnError from ndt-server logs on a single k8s node.

Approximately 2019-06-12 20:00 to 2019-06-14 16:00:

Read error counts:
```
      1  no route to host
      4  connection timed out
    624  connection reset by peer
```

Write error counts:
```
      1  permission denied
      7  no route to host
     75  connection timed out
    200  connection reset by peer
    271  broken pipe
```

General error counts:
```
      6 error: context deadline exceeded
     13 going away)
     15 error: No data
     57 error: strconv.Atoi: parsing "4 | 32 | 16": invalid syntax
     62 abnormal closure): unexpected EOF
    140 error: EOF
    295 error: unexpected end of JSON input
    604 no status)
   3268 error: No connection created
```

**Comment by pboothe** [comment]
Tasks to do to address this:
* Distinguish between errors and warnings. Errors cause us to have bad data. Warnings are errors which do not affect data.
* Wrap errors to ensure that every error message is traceable to the line in the ndt-server codebase from which it originated.
* Make the s2c code robust to clients which, due to clock skew, only allow us to fill the connection for 9.9 seconds.

**Comment by stephen-soltesz** [comment]
We have a BQ view library.soltesz_error_strings that summarizes the error strings:
https://console.cloud.google.com/bigquery?sq=581276032543:4ad694c44eff415da106567a873b7445

NOTE: that query pins the date range to 06-08 to 06-18.

**Comment by pboothe** [comment]
Error rates for ndt-server are now less than the error rates for legacy ndt for all client populations
