### ISSUE TITLE
Limit log sizes from docker images via cloud-config.yml

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/ndt-server#3]
The cloud-config.yml should set additional log size limits on all VMs.

https://access.redhat.com/solutions/2334181
`--log-opt max-size=50m --log-opt max-file=5`

Currently the NDT logs are consuming 10s of GBs over a few days.

In the mean time, we'll reduce logging to negligible levels.

**Comment by pboothe** [comment]
We've lost state on this. Unless @nkinkade remembers what this is about, we should close it.

**Comment by nkinkade** [comment]
I believe this may have had something to do with the TYO VMs and the disks filling up. I found some chatter in #ops-deployment in mid May 2018 (just a couple weeks before this issue) having to do with adding `vdlimit_*` metrics to the TYO VMs. If it didn't have to do with the TYO VMs, then I don't know what it was about. Assuming the former, we no longer even have the TYO VMs running, so this issue is now obsolete. Closing.
