### ISSUE TITLE
rate-limiter errors for very fast clients and fallback considerations

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt-server#334]
Good day,

Yesterday I was running tests from very fast clients to evaluate the performance impact of a change I implemented in the @ooni codebase for ndt7. As part of this investigation, I also used the official ndt7-client-go as part of this.

My setup was that `locate` could serve me two different sets of servers. One for which the download speed was ~5 Gbit/s and the other for which it was ~1 Gbit/s. The test box was inside GCE and the M-Lab site was Amsterdam.

As part of this work, I noticed that _all_ ~5 Gbit/s download tests were _always_ followed by an upload error, like this:

```
wss://ndt-mlab3-ams03.mlab-oti.measurement-lab.org/ndt/v7/upload?
access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjMtYW1zMDMubWxhYi1vdGkubWVhc3Vy
ZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE2MjM3NTM1NDcsImlzcyI6ImxvY2F0ZSIsInN1YiI6Im5kdCJ9.qW1BoUeGJS3nkoX-f2Nmbh2k-8FsUq94g
8-qibsnFENpjxwTcb1fTn44aKX2Eq2fe4rmOc6jsBL9MhUch9lPCQ
[     11.252821] <warn> measurement failed: map[error:websocket: bad handshake]
```

I asked @robertodauria to help me diagnose this issue and this is when he introduced me to the concept of a rate limiter for preventing clients from abusing the platform. Apparently, the rate limiter does not distinguish between the download and the upload bandwidth (AFAICT), therefore my very fast download test caused the subsequent upload test to fail.

I suppose it would instead be optimal to distinguish between the upload and download bandwidths.

As part of this investigation, with @robertodauria we also discussed whether it would make sense for a client to retry the failed upload with the subsequent server returned by `locate`. We concluded, however, that this may be confusing to people using `ndt7` to diagnose their own connections. There is an implicit assumption that a speed test would likely use the same path for download and upload. Breaking this assumption may complicate the life of someone who's trying to use `ndt7` in this way, even though the protocol in principle does not impose this constraint upon the clients.

(A related, nice-to-have kind of test would be that of trying all the nearby servers, so to provide a more clear picture of how the user connects with nearby data centers, but that's a different topic.)

**Comment by nosnilmot** [comment]
See also https://github.com/m-lab/ndt7-client-go/issues/57 and https://github.com/m-lab/ndt7-client-go/issues/58 which suggest that retrying the upload with a subsequent server returned by `locate` is the intended behaviour, but currently not working/implemented in the reference go client.

**Comment by robertodauria** [comment]
Thanks for this great summary!

>
> I suppose it would instead be optimal to distinguish between the upload and download bandwidths.
> 

I agree they should be treated separately by the rate limiter. This would still make the upload fail in the case the server is actually overloaded (by other clients) but since inbound traffic is generally lower than outbound that's very unlikely to happen.

> As part of this investigation, with @robertodauria we also discussed whether it would make sense for a client to retry the failed upload with the subsequent server returned by `locate`. We concluded, however, that this may be confusing to people using `ndt7` to diagnose their own connections. There is an implicit assumption that a speed test would likely use the same path for download and upload. Breaking this assumption may complicate the life of someone who's trying to use `ndt7` in this way, even though the protocol in principle does not impose this constraint upon the clients.
>

Retrying the whole download+upload measurement in those few cases where the server is getting too much inbound traffic from other clients would preserve the property that download+upload are run towards the same server (at the cost of an additional download measurement) and it would not require another call to the Locate service since we've already received 3 additional nearby servers to fall back on.

The access tokens provided by Locate are valid for two minutes, measurements last `10s + 10s + connection timeouts` at most so there should be ample time to attempt a complete measurement with at least another server in the worst-case scenario.

**Comment by laiyi-ohlsen** [comment]
@stephen-soltesz

**Comment by stephen-soltesz** [comment]
Functionality to eliminate this type of connection error is deploying to production today.

**Comment by stephen-soltesz** [comment]
Some portion of requests will still be blocked due to actual transmission rate above the configured threshold. But these events will no longer impact "upload" for ndt7 measurements. This looks like a roughly 50% reduction in Tx Controller rejection rates globally.

<img width="1773" alt="Screen Shot 2022-08-12 at 11 39 45 AM" src="https://user-images.githubusercontent.com/1085316/184391040-29981e75-c534-42c1-b421-1565bd0cdbbd.png">

**Comment by stephen-soltesz** [comment]
<img width="1695" alt="Screen Shot 2022-08-14 at 12 51 07 PM" src="https://user-images.githubusercontent.com/1085316/184549645-f5cbf75a-c000-4eaf-9b9d-8a932f7856e2.png">
